import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";

interface IServerSideProps {
  stuff: StuffType;
}

const Home: NextPage<IServerSideProps> = ({ stuff }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles["main-h1"]}>Stuff List</h1>

        <h2>{stuff.characters}</h2>
        <h2>{stuff.episodes}</h2>
        <h2>{stuff.locations}</h2>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

type StuffType = {
  characters: string;
  episodes: string;
  locations: string;
};

export const getStaticProps = async () => {
  try {
    const otherApi = "https://rickandmortyapi.com/api";
    const stuff: StuffType = await fetch(otherApi).then((res) => res.json());

    if (!stuff) {
      return {
        notFound: true,
      };
    }

    return {
      props: {
        stuff,
      },
      revalidate: 10,
    };
  } catch (error) {
    return {
      notFound: true,
    };
  }
};

export default Home;
